"use client"

import {FormEvent,useState} from "react"
import {useRouter} from "next/navigation"
import Logo from "@/app/components/Logo"

function iso(value:string){return value?new Date(value).toISOString():null}
export default function NewEventPage(){
  const router=useRouter(),[busy,setBusy]=useState(false),[error,setError]=useState("")
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);try{const response=await fetch("/admin/api/settings",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:form.get("name"),code:form.get("code"),venue:form.get("venue"),description:form.get("description"),starts_at:iso(String(form.get("starts_at")||"")),ends_at:iso(String(form.get("ends_at")||"")),timezone:"Europe/Rome"})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Creazione non riuscita.");router.push(`/admin/impostazioni/${data.event.code}`)}catch(cause){setError(cause instanceof Error?cause.message:"Errore inatteso.")}finally{setBusy(false)}}
  return <main className="min-h-screen bg-black px-4 py-8 text-white"><div className="mx-auto max-w-2xl"><div className="flex items-center justify-between"><Logo size="medium"/><button onClick={()=>router.back()} className="rounded-xl border border-white/10 px-4 py-3 text-sm font-black">INDIETRO</button></div><p className="mt-10 text-xs font-black uppercase tracking-[.2em] text-pink-400">Nuovo progetto</p><h1 className="mt-2 text-4xl font-black">Crea un nuovo evento</h1><p className="mt-3 text-zinc-400">Nascerà in modalità Bozza, senza partecipanti, chat, missioni o dati di test.</p>{error&&<p className="mt-5 rounded-2xl border border-red-400/30 bg-red-400/10 p-4 text-red-200">{error}</p>}<form onSubmit={submit} className="mt-7 grid gap-5 rounded-3xl border border-white/10 bg-white/[.05] p-6"><label className="text-sm font-bold">Nome evento<input name="name" required minLength={3} placeholder="Es. Zocyal Summer Party" className="mt-2 w-full rounded-xl bg-white p-4 text-black"/></label><label className="text-sm font-bold">Codice partecipazione<input name="code" required minLength={3} maxLength={24} pattern="[a-z0-9][a-z0-9_-]{2,23}" placeholder="es. summer26" onInput={e=>e.currentTarget.value=e.currentTarget.value.toLowerCase().replace(/[^a-z0-9_-]/g,"")} className="mt-2 w-full rounded-xl bg-white p-4 text-black"/></label><p className="-mt-3 text-xs text-zinc-500">Minuscole, numeri, trattino o underscore. Diventerà parte del link e del QR.</p><label className="text-sm font-bold">Luogo<input name="venue" placeholder="Nome locale e città" className="mt-2 w-full rounded-xl bg-white p-4 text-black"/></label><label className="text-sm font-bold">Descrizione<textarea name="description" rows={4} placeholder="Presentazione breve per i partecipanti" className="mt-2 w-full rounded-xl bg-white p-4 text-black"/></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Apertura<input name="starts_at" type="datetime-local" className="mt-2 w-full rounded-xl bg-white p-4 text-black"/></label><label className="text-sm font-bold">Chiusura<input name="ends_at" type="datetime-local" className="mt-2 w-full rounded-xl bg-white p-4 text-black"/></label></div><button disabled={busy} className="mt-2 rounded-xl bg-gradient-to-r from-fuchsia-600 via-pink-500 to-orange-400 px-6 py-4 text-lg font-black disabled:opacity-60">{busy?"CREAZIONE...":"CREA EVENTO IN BOZZA"}</button></form></div></main>
}
