"use client"

import {useEffect,useState} from "react"
import Logo from "@/app/components/Logo"

type EventItem={code:string;name:string;venue:string|null;status:"draft"|"open"|"closed";starts_at:string|null;ends_at:string|null}
const labels={draft:"BOZZA",open:"APERTO",closed:"TERMINATO"}
export default function EventsPage(){
  const [events,setEvents]=useState<EventItem[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("")
  useEffect(()=>{void fetch("/admin/api/events",{credentials:"same-origin",cache:"no-store"}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);setEvents(body.events||[])}).catch(cause=>setError(cause instanceof Error?cause.message:"Errore inatteso.")).finally(()=>setLoading(false))},[])
  return <main className="min-h-screen bg-black px-4 py-8 text-white"><div className="mx-auto max-w-6xl"><header className="flex flex-col items-start justify-between gap-5 sm:flex-row sm:items-center"><div><Logo size="medium"/><p className="mt-5 text-xs font-black uppercase tracking-[.2em] text-pink-400">Amministrazione</p><h1 className="mt-2 text-4xl font-black">I miei eventi</h1></div><div className="flex gap-2"><a href="/admin/events/new" className="rounded-2xl bg-gradient-to-r from-fuchsia-600 via-pink-500 to-orange-400 px-5 py-4 font-black">＋ CREA NUOVO EVENTO</a><form action="/admin/api/logout" method="post"><button className="rounded-2xl border border-white/10 px-5 py-4 font-black">ESCI</button></form></div></header>{error&&<p className="mt-7 rounded-2xl border border-red-400/30 bg-red-400/10 p-4 text-red-200">{error}</p>}{loading&&<p className="mt-8 text-zinc-400">Caricamento eventi...</p>}{!loading&&!error&&<section className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{events.map(event=><article key={event.code} className="rounded-3xl border border-white/10 bg-white/[.05] p-6"><div className="flex items-start justify-between gap-3"><div><h2 className="text-2xl font-black">{event.name}</h2><p className="mt-2 text-sm font-bold text-pink-300">Codice: {event.code}</p></div><span className={`rounded-full px-3 py-1 text-xs font-black ${event.status==="open"?"bg-green-400/15 text-green-300":event.status==="draft"?"bg-amber-400/15 text-amber-300":"bg-zinc-700 text-zinc-300"}`}>{labels[event.status]}</span></div><p className="mt-4 text-zinc-400">📍 {event.venue||"Luogo non indicato"}</p><p className="mt-2 text-sm text-zinc-500">{event.starts_at?new Date(event.starts_at).toLocaleString("it-IT"):"Apertura non impostata"}</p>{event.code==="test"&&<p className="mt-4 rounded-xl border border-sky-400/20 bg-sky-400/10 p-3 text-xs font-black text-sky-300">AMBIENTE DI PROVA</p>}<div className="mt-5 grid grid-cols-2 gap-2"><a href={`/admin/dashboard/${event.code}`} className="rounded-xl bg-white px-4 py-3 text-center text-sm font-black text-black">GESTISCI</a><a href={`/admin/impostazioni/${event.code}`} className="rounded-xl border border-white/10 px-4 py-3 text-center text-sm font-black">IMPOSTAZIONI</a></div></article>)}{events.length===0&&<p className="text-zinc-400">Nessun evento. Creane uno per iniziare.</p>}</section>}</div></main>
}
