"use client"

import { FormEvent, useCallback, useEffect, useState } from "react"
import { useParams } from "next/navigation"
import Sidebar from "@/app/admin/components/Sidebar"
import PremiumBackdrop from "@/app/components/PremiumBackdrop"

const INTERESTS = ["Conoscere tante persone", "Stare con pochi amici", "Ballare e divertirti", "Parlare e conoscere persone", "Avventura e sorprese", "Relax e tranquillità", "Fare nuove amicizie", "Trovare una connessione speciale"]
type Invite = { id:string; status:"pending"|"accepted"|"declined"|"joined"; points_awarded:number; participant:{id:string;nickname:string|null;avatar_url:string|null}|null }
type Table = { id:string;name:string;game:string;interest_tags:string[];points_reward:number;max_participants:number;status:"open"|"closed";invitations:Invite[] }

export default function GameTablesAdminPage() {
  const { code: raw } = useParams<{code:string}>(), code = raw.toLowerCase()
  const [tables,setTables]=useState<Table[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState("")
  const load=useCallback(async()=>{const response=await fetch(`/admin/api/game-tables?code=${encodeURIComponent(code)}`,{cache:"no-store"});const payload=await response.json();if(!response.ok)throw new Error(payload.error);setTables(payload.tables)},[code])
  useEffect(()=>{const initial=window.setTimeout(()=>{load().catch(error=>setMessage(error.message)).finally(()=>setLoading(false))},0);const timer=setInterval(()=>{if(!document.hidden)void load()},30000);return()=>{clearTimeout(initial);clearInterval(timer)}},[load])
  async function mutate(body:Record<string,unknown>){setBusy(true);setMessage("");try{const response=await fetch("/admin/api/game-tables",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({event_code:code,...body})});const payload=await response.json();if(!response.ok)throw new Error(payload.error);await load();return payload}catch(error){setMessage(error instanceof Error?error.message:"Operazione non riuscita.");return null}finally{setBusy(false)}}
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const payload=await mutate({action:"create",name:form.get("name"),game:form.get("game"),points_reward:Number(form.get("points")),interest_tags:form.getAll("interests")});if(payload){setMessage(`Tavolo creato: ${payload.invited} inviti compatibili inviati.`);event.currentTarget.reset()}}
  return <div className="flex min-h-screen bg-[#050306] text-white"><Sidebar/><main className="relative min-w-0 flex-1 px-4 pb-12 pt-20 lg:p-8"><PremiumBackdrop orbs={false}/><div className="relative mx-auto max-w-7xl"><header><p className="premium-eyebrow">Social games</p><h1 className="premium-title mt-3 text-4xl font-black sm:text-6xl">Tavoli gioco.</h1><p className="mt-3 text-white/50">Invita persone compatibili, fino a 6 posti per tavolo.</p></header>
  {message&&<p role="status" className="mt-5 rounded-2xl border border-pink-400/20 bg-pink-400/10 p-4 text-pink-100">{message}</p>}
  <form onSubmit={create} className="premium-glass mt-7 rounded-[2rem] p-5 sm:p-7"><h2 className="text-2xl font-black">Crea un tavolo</h2><div className="mt-5 grid gap-4 md:grid-cols-3"><label className="text-sm text-white/70">Nome tavolo<input name="name" required maxLength={120} className="mt-2 w-full rounded-xl bg-white p-3 text-black" placeholder="Tavolo Luna"/></label><label className="text-sm text-white/70">Gioco<input name="game" required maxLength={120} className="mt-2 w-full rounded-xl bg-white p-3 text-black" placeholder="Obbligo o Verità"/></label><label className="text-sm text-white/70">Punti presenza<input name="points" type="number" min="1" max="10" defaultValue="3" required className="mt-2 w-full rounded-xl bg-white p-3 text-black"/></label></div><fieldset className="mt-5"><legend className="text-sm font-bold">Interessi compatibili</legend><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{INTERESTS.map(item=><label key={item} className="flex items-center gap-3 rounded-xl border border-white/10 bg-white/[.04] p-3 text-sm"><input type="checkbox" name="interests" value={item}/>{item}</label>)}</div></fieldset><button disabled={busy} className="premium-cta mt-5 rounded-full px-6 py-3 font-black">{busy?"CREAZIONE…":"CREA E INVITA"}</button></form>
  <section className="mt-8 grid gap-5 xl:grid-cols-2">{loading?<p>Caricamento…</p>:tables.map(table=>{const occupied=table.invitations.filter(i=>i.status==="accepted"||i.status==="joined").length;return <article key={table.id} className="rounded-[2rem] border border-white/10 bg-white/[.035] p-5"><div className="flex justify-between gap-4"><div><p className="text-xs font-black uppercase text-pink-300">{table.game}</p><h2 className="mt-1 text-2xl font-black">{table.name}</h2><p className="mt-2 text-sm text-white/45">{occupied}/6 posti · +{table.points_reward} punti alla presenza</p></div><span className="text-3xl">🎲</span></div><div className="mt-4 flex flex-wrap gap-2">{table.interest_tags.map(tag=><span key={tag} className="rounded-full bg-white/[.06] px-3 py-1 text-xs text-white/60">{tag}</span>)}</div><div className="mt-5 grid gap-2">{table.invitations.map(invite=><div key={invite.id} className="flex items-center justify-between gap-3 rounded-xl border border-white/8 p-3"><span className="truncate text-sm font-bold">{invite.participant?.nickname||"Partecipante"}</span><div className="flex items-center gap-2"><span className="text-xs text-white/45">{{pending:"In attesa",accepted:"Accettato",declined:"Rifiutato",joined:"Presente"}[invite.status]}</span>{invite.status==="accepted"&&<button disabled={busy} onClick={()=>void mutate({action:"mark_joined",invitation_id:invite.id})} className="rounded-full bg-emerald-300 px-3 py-2 text-[10px] font-black text-black">CONFERMA PRESENZA</button>}</div></div>)}{!table.invitations.length&&<p className="text-sm text-white/40">Nessun partecipante compatibile.</p>}</div>{table.status==="open"&&<button disabled={busy} onClick={()=>void mutate({action:"close",table_id:table.id})} className="mt-5 rounded-full border border-white/10 px-4 py-2 text-xs font-black text-white/60">CHIUDI TAVOLO</button>}</article>})}</section></div></main></div>
}
