"use client"

import { useCallback, useEffect, useRef, useState } from "react"
import { useParams, useRouter } from "next/navigation"
import { publicSupabase, supabase } from "@/lib/supabase"
import { resolveCurrentParticipant } from "@/app/lib/participant-session"
import Logo from "@/app/components/Logo"
import PremiumBackdrop from "@/app/components/PremiumBackdrop"
import { ActionFeedback, EmptyState, EventBackButton, LiveSyncStatus } from "@/app/components/EventUi"

type Invitation = { id:string;status:"pending"|"accepted"|"declined"|"joined";points_awarded:number;table_id:string;table:{id:string;name:string;game:string;interest_tags:string[];points_reward:number;max_participants:number;status:"open"|"closed"}|null }

export default function GameTablesPage(){
  const {code:raw}=useParams<{code:string}>(),code=raw.toLowerCase()
  const router=useRouter()
  const [participantId,setParticipantId]=useState(""),[invitations,setInvitations]=useState<Invitation[]>([]),[points,setPoints]=useState(0),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[message,setMessage]=useState(""),[updatedAt,setUpdatedAt]=useState<Date|null>(null)
  const actionLock=useRef(false)
  const load=useCallback(async(id:string)=>{const [invitesResult,pointsResult]=await Promise.all([supabase.from("game_table_invitations").select("id,status,points_awarded,table_id,table:game_tables(id,name,game,interest_tags,points_reward,max_participants,status)").eq("participant_id",id).order("invited_at",{ascending:false}),supabase.rpc("get_participant_points_for_event",{p_event_code:code})]);if(invitesResult.error)throw invitesResult.error;if(pointsResult.error)throw pointsResult.error;const loaded=(invitesResult.data||[]) as unknown as Invitation[];setInvitations(loaded);setPoints(typeof pointsResult.data==="number"?pointsResult.data:0);setUpdatedAt(new Date())},[code])
  useEffect(()=>{let active=true;let currentId="";let channel:ReturnType<typeof supabase.channel>|null=null;let refreshTimer:number|null=null;const refresh=()=>{if(!active||!currentId)return;if(refreshTimer!==null)window.clearTimeout(refreshTimer);refreshTimer=window.setTimeout(()=>{refreshTimer=null;void load(currentId).catch(()=>undefined)},150)};(async()=>{try{const event=await publicSupabase.from("events").select("experience_mode").eq("code",code).maybeSingle();if(event.data?.experience_mode==="caribbean"){router.replace(`/evento/${code}/balla`);return}const id=await resolveCurrentParticipant(code);if(!id)throw new Error("Profilo partecipante non trovato.");if(!active)return;currentId=id;setParticipantId(id);await load(id);channel=supabase.channel(`game-tables-${id}`).on("postgres_changes",{event:"*",schema:"public",table:"game_table_invitations",filter:`participant_id=eq.${id}`},refresh).subscribe(status=>{if(status==="SUBSCRIBED")refresh()})}catch(error){if(active)setMessage(error instanceof Error?error.message:"Impossibile caricare gli inviti.")}finally{if(active)setLoading(false)}})();const fallback=window.setInterval(()=>{if(!document.hidden)refresh()},30000);const visible=()=>{if(!document.hidden)refresh()};document.addEventListener("visibilitychange",visible);window.addEventListener("focus",visible);window.addEventListener("online",visible);return()=>{active=false;if(refreshTimer!==null)window.clearTimeout(refreshTimer);window.clearInterval(fallback);document.removeEventListener("visibilitychange",visible);window.removeEventListener("focus",visible);window.removeEventListener("online",visible);if(channel)void supabase.removeChannel(channel)}},[code,load,router])
  async function respond(id:string,accept:boolean){if(actionLock.current)return;actionLock.current=true;setBusy(id);setMessage("");try{const {data,error}=await supabase.rpc("respond_game_table_invitation",{p_invitation_id:id,p_accept:accept});if(error){setMessage(error.message.includes("Table full")?"Il tavolo ha già raggiunto il limite di 6 persone.":"Non è stato possibile rispondere all'invito.")}else if(participantId){await load(participantId);const result=(data||{}) as {points_awarded?:number};setMessage(accept?`Posto riservato! +${result.points_awarded||0} punti assegnati.`:"Invito rifiutato.")}}finally{actionLock.current=false;setBusy("")}}
  return <main className="relative min-h-screen overflow-hidden bg-[#050306] px-4 pb-28 pt-8 text-white sm:px-6"><PremiumBackdrop/><div className="relative mx-auto max-w-5xl"><div className="flex items-center justify-between gap-4"><EventBackButton href={`/evento/${code}/home`} label="Torna alla home"/><Logo size="small"/></div><header className="mt-10"><p className="premium-eyebrow">Inviti live</p><div className="flex flex-wrap items-end justify-between gap-5"><div><h1 className="premium-title mt-3 text-4xl font-black sm:text-6xl">Tavoli gioco.</h1><p className="mt-4 max-w-2xl text-white/50">Accetta un invito compatibile con te. Ogni tavolo ha al massimo 6 partecipanti; i punti arrivano quando lo staff conferma la tua presenza.</p><div className="mt-3"><LiveSyncStatus updatedAt={updatedAt} label="Inviti aggiornati"/></div></div><div className="rounded-2xl border border-orange-300/20 bg-orange-300/10 px-5 py-4 text-right"><p className="text-xs font-black uppercase tracking-wider text-orange-200/70">I tuoi punti</p><p className="mt-1 text-3xl font-black text-orange-300">{points}</p></div></div></header><ActionFeedback message={message} tone={/riservato|rifiutato/i.test(message)?"success":"error"} className="mt-6"/>
  <section className="mt-8 grid gap-5 md:grid-cols-2">{loading?<div className="h-56 animate-pulse rounded-[2rem] bg-white/[.04]"/>:invitations.map(invite=>{const table=invite.table;if(!table)return null;return <article key={invite.id} className="premium-card-lift rounded-[2rem] border border-white/10 bg-white/[.04] p-6"><div className="flex justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-wider text-orange-300">{table.game}</p><h2 className="mt-2 text-2xl font-black">{table.name}</h2></div><span className="text-4xl">🎲</span></div><div className="mt-4 flex flex-wrap gap-2">{table.interest_tags.map(tag=><span key={tag} className="rounded-full bg-pink-400/10 px-3 py-1 text-xs text-pink-200">{tag}</span>)}</div><p className="mt-5 text-sm text-white/50">Premio prenotazione: <strong className="text-orange-300">+{table.points_reward} punti</strong></p>{invite.status==="pending"&&table.status==="open"?<div className="mt-6 grid grid-cols-2 gap-3"><button disabled={busy===invite.id} onClick={()=>void respond(invite.id,true)} className="premium-cta rounded-full px-4 py-3 font-black">ACCETTA</button><button disabled={busy===invite.id} onClick={()=>void respond(invite.id,false)} className="rounded-full border border-white/15 px-4 py-3 font-black text-white/60">RIFIUTA</button></div>:<p className={`mt-6 rounded-xl p-3 text-center text-sm font-black ${invite.status==="joined"?"bg-emerald-400/10 text-emerald-300":invite.status==="accepted"?"bg-sky-400/10 text-sky-300":"bg-white/[.05] text-white/45"}`}>{invite.status==="accepted"?`POSTO RISERVATO · +${invite.points_awarded||table.points_reward} PUNTI ASSEGNATI`:invite.status==="joined"?`PRESENZA CONFERMATA · +${invite.points_awarded} PUNTI`:invite.status==="declined"?"INVITO RIFIUTATO":"TAVOLO CHIUSO"}</p>}</article>})}{!loading&&!invitations.length&&<EmptyState icon="🎲" title="Nessun invito al momento" description="Ti avviseremo automaticamente quando nasce un tavolo compatibile con te." className="md:col-span-2"/>}</section></div></main>
}
