"use client"

import { ChangeEvent, FormEvent, useCallback, useEffect, useRef, useState } from "react"
import { useParams } from "next/navigation"
import Image from "next/image"
import { QRCodeCanvas } from "qrcode.react"
import Sidebar from "@/app/admin/components/Sidebar"

type EventSettings={name:string;venue:string|null;code:string;description:string;starts_at:string|null;ends_at:string|null;timezone:string;status:"draft"|"open"|"closed";experience_mode:"standard"|"inclusive"|"caribbean";venue_logo_url:string|null;venue_poster_url:string|null;updated_at:string}
const LOGO_MAX_SIZE=3*1024*1024,POSTER_MAX_SIZE=8*1024*1024,LOGO_UPLOAD_SIZE=900*1024,POSTER_UPLOAD_SIZE=2800*1024
function localDate(value:string|null){if(!value)return "";const date=new Date(value);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16)}
function iso(value:string){return value?new Date(value).toISOString():null}
async function optimizeImage(file:File,maxBytes:number,maxDimension:number){if(!file.size||file.size<=maxBytes)return file;const bitmap=await createImageBitmap(file);let scale=Math.min(1,maxDimension/Math.max(bitmap.width,bitmap.height));try{for(let resize=0;resize<5;resize+=1){const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext("2d")?.drawImage(bitmap,0,0,canvas.width,canvas.height);for(const quality of [.9,.8,.7,.6,.5]){const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,"image/webp",quality));if(blob&&blob.size<=maxBytes)return new File([blob],`${file.name.replace(/\.[^.]+$/," ").trim()||"immagine"}.webp`,{type:"image/webp",lastModified:file.lastModified})}scale*=.75}}finally{bitmap.close()}throw new Error("Non siamo riusciti a ottimizzare l'immagine. Prova con un file piÃ¹ leggero.")}

export default function SettingsPage(){
  const {code:raw}=useParams<{code:string}>(),code=raw.toLowerCase()
  const [event,setEvent]=useState<EventSettings|null>(null),[error,setError]=useState(""),[success,setSuccess]=useState(""),[busy,setBusy]=useState(false)
  const [publicLink,setPublicLink]=useState("")
  const [logoPreview,setLogoPreview]=useState(""),[posterPreview,setPosterPreview]=useState("")
  const qrRef=useRef<HTMLDivElement>(null)
  const load=useCallback(async()=>{const response=await fetch(`/admin/api/settings?code=${encodeURIComponent(code)}`,{credentials:"same-origin",cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"Impossibile caricare le impostazioni.");setEvent(data.event)},[code])
  useEffect(()=>{const initial=window.setTimeout(()=>{setPublicLink(`${window.location.origin}/evento/${code}`);void load().catch(e=>setError(e instanceof Error?e.message:"Errore inatteso."))},0);return()=>window.clearTimeout(initial)},[load,code])

  async function save(e:FormEvent<HTMLFormElement>){
    e.preventDefault();if(!event)return;setBusy(true);setError("");setSuccess("")
    const form=new FormData(e.currentTarget),status=String(form.get("status")),logo=form.get("venue_logo"),poster=form.get("venue_poster")
    if(logo instanceof File&&logo.size>LOGO_MAX_SIZE){setError("Il logo supera 3 MB.");setBusy(false);return}
    if(poster instanceof File&&poster.size>POSTER_MAX_SIZE){setError("La locandina supera 8 MB.");setBusy(false);return}
    form.set("code",code);form.set("starts_at",iso(String(form.get("starts_at")||""))||"");form.set("ends_at",iso(String(form.get("ends_at")||""))||"")
    if(status==="closed"&&!window.confirm("Terminare l'evento? I nuovi partecipanti non potranno più entrare.")){setBusy(false);return}
    try{if(logo instanceof File&&logo.size)form.set("venue_logo",await optimizeImage(logo,LOGO_UPLOAD_SIZE,1200));if(poster instanceof File&&poster.size)form.set("venue_poster",await optimizeImage(poster,POSTER_UPLOAD_SIZE,2200));const response=await fetch("/admin/api/settings",{method:"PATCH",credentials:"same-origin",body:form});const data=await response.json().catch(()=>({}));if(response.status===413)throw new Error("Le immagini sono troppo pesanti per essere caricate.");if(!response.ok)throw new Error(data.error||"Salvataggio non riuscito.");setEvent(data.event);setLogoPreview("");setPosterPreview("");setSuccess("Impostazioni e immagini salvate correttamente.")}catch(e){setError(e instanceof Error?e.message:"Errore inatteso.")}finally{setBusy(false)}
  }

  function preview(e:ChangeEvent<HTMLInputElement>,setter:(value:string)=>void){const file=e.currentTarget.files?.[0];setter(file?URL.createObjectURL(file):"")}

  function downloadQr(){const canvas=qrRef.current?.querySelector("canvas");if(!canvas)return;const anchor=document.createElement("a");anchor.download=`zocyal-${code}-qr.png`;anchor.href=canvas.toDataURL("image/png");anchor.click()}
  return <div className="flex min-h-screen bg-black text-white"><Sidebar/><main className="min-w-0 flex-1 px-4 pb-16 pt-20 lg:p-8"><div className="mx-auto max-w-4xl">
    <p className="text-xs font-black uppercase tracking-[.2em] text-pink-400">Gestione evento</p><h1 className="mt-2 text-4xl font-black">Impostazioni</h1>
    {error&&<p className="mt-5 rounded-2xl border border-red-400/30 bg-red-400/10 p-4 text-red-200">{error}</p>}{success&&<p className="mt-5 rounded-2xl border border-green-400/30 bg-green-400/10 p-4 text-green-200">{success}</p>}{!event&&!error&&<p className="mt-8 text-zinc-400">Caricamento...</p>}
    {event&&<form onSubmit={save} className="mt-7 grid gap-6">
      <section className="rounded-3xl border border-white/10 bg-white/[.05] p-6"><h2 className="text-2xl font-black">Informazioni pubbliche</h2><label className="mt-5 block text-sm font-bold">Nome evento<input name="name" required minLength={3} defaultValue={event.name} className="mt-2 w-full rounded-xl bg-white p-3 text-black"/></label><label className="mt-4 block text-sm font-bold">Luogo<input name="venue" defaultValue={event.venue||""} className="mt-2 w-full rounded-xl bg-white p-3 text-black"/></label><label className="mt-4 block text-sm font-bold">Descrizione<textarea name="description" defaultValue={event.description||""} rows={4} className="mt-2 w-full rounded-xl bg-white p-3 text-black"/></label></section>
      <section className="rounded-3xl border border-white/10 bg-white/[.05] p-6"><h2 className="text-2xl font-black">Logo e locandina</h2><p className="mt-2 text-sm text-zinc-400">Lascia un campo vuoto per mantenere l&apos;immagine attuale.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="rounded-2xl border border-dashed border-white/20 bg-black/25 p-4"><span className="text-xs font-black uppercase tracking-wider text-pink-300">Logo · max 3 MB</span><input name="venue_logo" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>preview(e,setLogoPreview)} className="mt-4 block w-full text-xs text-zinc-400 file:mr-3 file:rounded-full file:border-0 file:bg-white file:px-3 file:py-2 file:font-black file:text-black"/>{(logoPreview||event.venue_logo_url)&&<Image src={logoPreview||event.venue_logo_url||""} alt="Anteprima logo" width={640} height={288} unoptimized={Boolean(logoPreview)} className="mt-4 h-36 w-full rounded-xl bg-zinc-800 object-contain p-3"/>}</label><label className="rounded-2xl border border-dashed border-white/20 bg-black/25 p-4"><span className="text-xs font-black uppercase tracking-wider text-orange-200">Locandina · max 8 MB</span><input name="venue_poster" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>preview(e,setPosterPreview)} className="mt-4 block w-full text-xs text-zinc-400 file:mr-3 file:rounded-full file:border-0 file:bg-white file:px-3 file:py-2 file:font-black file:text-black"/>{(posterPreview||event.venue_poster_url)&&<Image src={posterPreview||event.venue_poster_url||""} alt="Anteprima locandina" width={600} height={800} unoptimized={Boolean(posterPreview)} className="mt-4 aspect-[3/4] w-full rounded-xl object-cover"/>}</label></div></section>
      <section className="rounded-3xl border border-white/10 bg-white/[.05] p-6"><h2 className="text-2xl font-black">Accesso e orari</h2><label className="mt-5 block text-sm font-bold">Codice evento<input readOnly value={event.code} className="mt-2 w-full rounded-xl border border-white/10 bg-zinc-900 p-3 text-zinc-300"/></label><p className="mt-2 text-xs text-zinc-500">Il codice è protetto perché è già collegato a profili, missioni, premi e QR.</p><div className="mt-4 rounded-2xl border border-white/10 bg-black/25 p-4"><p className="text-xs font-black uppercase tracking-[.16em] text-pink-300">Tipo di esperienza</p><p className="mt-2 text-lg font-black">{event.experience_mode==="inclusive"?"Evento inclusivo":"Evento standard"}</p><p className="mt-2 text-xs leading-5 text-zinc-500">Scelto durante la creazione dell&apos;evento.</p></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Apertura<input name="starts_at" type="datetime-local" defaultValue={localDate(event.starts_at)} className="mt-2 w-full rounded-xl bg-white p-3 text-black"/></label><label className="text-sm font-bold">Chiusura<input name="ends_at" type="datetime-local" defaultValue={localDate(event.ends_at)} className="mt-2 w-full rounded-xl bg-white p-3 text-black"/></label></div><label className="mt-4 block text-sm font-bold">Fuso orario<select name="timezone" defaultValue={event.timezone||"Europe/Rome"} className="mt-2 w-full rounded-xl bg-white p-3 text-black"><option value="Europe/Rome">Italia · Europe/Rome</option></select></label><label className="mt-4 block text-sm font-bold">Stato<select name="status" defaultValue={event.status} className="mt-2 w-full rounded-xl bg-white p-3 text-black"><option value="draft">Bozza · ingressi chiusi</option><option value="open">Aperto · ingressi consentiti</option><option value="closed">Terminato · ingressi chiusi</option></select></label></section>
      <section className="rounded-3xl border border-white/10 bg-white/[.05] p-6"><div className="grid items-center gap-6 sm:grid-cols-[1fr_auto]"><div><p className="text-xs font-black uppercase tracking-[.18em] text-pink-400">Ingresso partecipanti</p><h2 className="mt-2 text-2xl font-black">Link e QR Code</h2><p className="mt-3 text-sm leading-6 text-zinc-400">Mostra il QR all&apos;ingresso o stampalo: apre direttamente la pagina dell&apos;evento.</p><p className="mt-4 break-all rounded-xl bg-black/40 p-4 text-sm text-pink-300">{publicLink||`/evento/${code}`}</p><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={()=>void navigator.clipboard.writeText(publicLink).then(()=>setSuccess("Link copiato."))} className="rounded-xl border border-pink-400/30 px-4 py-3 font-black text-pink-200">COPIA LINK</button><button type="button" onClick={downloadQr} className="rounded-xl bg-white px-4 py-3 font-black text-black">SCARICA QR</button></div></div>{publicLink&&<div ref={qrRef} className="mx-auto rounded-3xl bg-white p-5"><QRCodeCanvas value={publicLink} size={210} level="H" marginSize={1} aria-label={`QR Code evento ${event.name}`}/><p className="mt-3 max-w-[210px] text-center text-sm font-black text-black">{event.name}<br/><span className="text-xs font-bold text-zinc-500">Codice: {event.code}</span></p></div>}</div></section>
      <button disabled={busy} className="rounded-2xl bg-gradient-to-r from-fuchsia-600 via-pink-500 to-orange-400 px-6 py-4 text-lg font-black disabled:opacity-60">{busy?"SALVATAGGIO...":"SALVA IMPOSTAZIONI"}</button>
    </form>}
  </div></main></div>
}
